---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=false

resources:
- osc-namespace.yaml
- trustee-namespace.yaml
- osc-operatorgroup.yaml
- trustee-operatorgroup.yaml
- osc-subscription.yaml
- trustee-subscription.yaml
